### ISSUE TITLE
No SpaceAfterComma for multiple lines

### ISSUE THREAD

**Issue by Harmageddon** [brigade/scss-lint#196]
Hi!

I have several declarations that are split over two or more lines, with a comma at the end of the line:

```
    box-shadow: 0 0 .1em rgba($color - #555, .3) inset,
      0 0 .1em rgba($color - #555, .5);
```

The SpaceAfterComma wants me to add a space after the comma in the first line, which seems not very useful to me.

**Comment by jadjoubran** [comment]
We faced the issue here, 2 of my developers have this issue on mac where as on windows we're not having this issue.
The line endings are \r\n (windows)

**Comment by sds** [comment]
Hey @jadjoubran, this is a pretty old issue. Are you still having problems with the latest version of `scss-lint`? (0.37.0 at the time of writing)

**Comment by jadjoubran** [comment]
$ scss-lint -v
scss-lint 0.37.0
on my windows Machine

Here's a more thorough explanation:

We have a `fonts.scss` file that contains something similar to the following:

    @font-face {
	font-family: 'Open Sans';
	src: url('/fonts/OpenSans-Regular-webfont.eot');
	src: url('/fonts/OpenSans-Regular-webfont.eot?#iefix') format('embedded-opentype'),
	url('/fonts/OpenSans-Regular-webfont.woff2') format('woff2'),
	url('/fonts/OpenSans-Regular-webfont.woff') format('woff'),
	url('/fonts/OpenSans-Regular-webfont.ttf') format('truetype'),
	url('/fonts/OpenSans-Regular-webfont.svg#open_sansregular') format('svg');
	font-weight: normal;
	font-style: normal;
    }

.scss-lint.yml:

    SpaceAfterComma:
      enabled: true

Another thing that you need to consider is that line endines in `fonts.scss` is CRLF and the error only happens on Ubuntu and Mac (so Unix shell only). No errors on windows.

You might think that converting the line endings to LF would fix it, but I thought that it would be awkward as well because you'll then have to add a space at the end of the line which is useless (not sure of this because I haven't tried it).

Let me know if you want more information!
Thanks
