### ISSUE TITLE
Auto fix minor issues (w)

### ISSUE THREAD

**Issue by peavers** [brigade/scss-lint#282]
Might be a bit of a silly question - is it possible to auto correct minor issues much like fixmyjs?

**Comment by evoactivity** [comment]
Could this postcss project help with this?
https://github.com/postcss/postcss-scss

**Comment by thegranddesign** [comment]
@sds is this a new addition to the Sass library since this was discussed? http://sass-lang.com/documentation/Sass/SCSS/Parser.html

**Comment by sds** [comment]
@evoactivity No, that doesn't expose a parse tree outside of the JavaScript runtime. Since it is written in JavaScript, integration would be difficult except via a command line interface of some kind. Even then, it does not support "rewriting" the parse tree and re-serializing back to SCSS.

@thegranddesign: No, the problem is not parsing. The problem is being able to modify the parse tree and serialize it back into code without inadvertently changing the rest of the indentation/formatting in the document.

`Sass::Tree::Node`'s `to_sass` method is not a 1:1 mapping of the original source code that generated the `Sass::Tree::Node`, making it impractical for use in an auto-correction feature.
