### ISSUE TITLE
Does not appear to work with ruby 1.8.7

### ISSUE THREAD

**Issue by asottile** [brigade/scss-lint#32]
```
asottile@asottile$ ruby --version
ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]

asottile@asottile$ scss-lint --help
/usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require': /var/lib/gems/1.8/gems/scss-lint-0.8.0/lib/scss_lint/linter/single_line_per_selector_linter.rb:28: syntax error, unexpected '\n' (SyntaxError)
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from /var/lib/gems/1.8/gems/scss-lint-0.8.0/lib/scss_lint.rb:20
    from /var/lib/gems/1.8/gems/scss-lint-0.8.0/lib/scss_lint.rb:19:in `each'
    from /var/lib/gems/1.8/gems/scss-lint-0.8.0/lib/scss_lint.rb:19
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from /var/lib/gems/1.8/gems/scss-lint-0.8.0/bin/scss-lint:3
    from /usr/local/bin/scss-lint:19:in `load'
    from /usr/local/bin/scss-lint:19
```

**Comment by nelson6e65** [comment]
There is not a version compatible with ruby 1.8?
```
ruby 1.8.7 (2011-06-30 patchlevel 352) [i686-linux]
```


I'm using Ubuntu (wich repositories always are outdated ._.)

And I'm trying to compile ruby, but... I'm getting errors in each versions I try (not found solution yet). :disappointed: 
```
make[2]: *** [ossl_ssl.o] Error 1
make[2]: se sale del directorio «/usr/local/src/ruby-2.1.3/ext/openssl»
make[1]: *** [ext/openssl/all] Error 2
make[1]: se sale del directorio «/usr/local/src/ruby-2.1.3»
make: *** [build-ext] Error 2
!!! Compiling ruby 2.1.3 failed!
```

**Comment by srawlins** [comment]
I don't think anyone recommends using the system's Ruby on Linux or OS X or any other OS, nor compiling Ruby by source. Try [rbenv](https://github.com/sstephenson/rbenv) or [RVM](https://rvm.io/).

**Comment by nelson6e65** [comment]
Yes, I'm using [ruby-install](https://github.com/postmodern/ruby-install). 

But I'll try RVM.

**Comment by asottile** [comment]
Try installing openssl-dev?

**Comment by nelson6e65** [comment]
```
$ openssl version
OpenSSL 1.0.2d 9 Jul 2015
```

```
$ sudo apt-get update

$ sudo apt-get install openssl-dev
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
E: No se ha podido localizar el paquete openssl-dev
```

(Sorry, my sistem is in spanish, but aparently `openssl-dev` package is not found).

**Comment by sds** [comment]
`scss-lint` [supports only Ruby 1.9.3+](https://github.com/brigade/scss-lint/blob/v0.42.2/scss_lint.gemspec#L26) since [Ruby 1.8.7 was EOLed in July 2014](https://www.ruby-lang.org/en/news/2014/07/01/eol-for-1-8-7-and-1-9-2/).

Technically, [Ruby 1.9.3 has also been EOLed as of February 2015](https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/), so we should probably drop support for it as well. Having said that, it is not as much of a burden to support 1.9.3 as it was to support 1.8.7&mdash;most language features are still available, and the new features introduced in Ruby 2 aren't something we're missing (yet).

Would strongly advise anyone doing serious development with Ruby to upgrade to at least Ruby 2.
