### ISSUE TITLE
Possible issue with Ruby 2.2.1

### ISSUE THREAD

**Issue by justin808** [brigade/scss-lint#438]
```
NoMethodError: private method `color' called for "app/assets/stylesheets/_feedbacker-overrides.scss":String
```

For some reason the rainbow mixin on strings is not working. This seems to only happen for me when running `bundle exec rake scss_lint`

I'm initializing the rake task like:

```
  require "scss_lint/rake_task"

  SCSSLint::RakeTask.new do |t|
    t.files = ["app/assets/stylesheets/", "client/assets/stylesheets/"]
  end
```

Running scss-lint on the command line works fine.

**Comment by sds** [comment]
Hey @justin808, thanks for the report.

I'm having trouble reproducing this locally (even with Ruby 2.2.1). You're right that the Rainbow string extensions aren't getting loaded, but that doesn't seem to make sense since we explicitly `require 'scss-lint/cli'` [in the Rake task](https://github.com/brigade/scss-lint/blob/279ff992183add0f6a5c63e51e0be8159fe194b5/lib/scss_lint/rake_task.rb#L61), which runs `require 'rainbow/ext/string'`.

Does your `Gemfile.lock` list `rainbow (2.0.0)` in it, or some other version? If everything looks fine I might have to lean on you to submit a pull request that fixes the problem on your end, though at this point it seems like it's likely a local issue.

**Comment by sds** [comment]
Closing due to lack of response. Feel free to reopen if more information can be provided!

**Comment by justin808** [comment]
@sds Sorry about the slow response. The issue was https://github.com/bbatsov/rubocop/issues/1839

**Comment by sds** [comment]
Thanks for the clarification, @justin808.

I would like to remove `scss-lint`'s dependency on the `rainbow` gem once we address #364, so this should no longer be an issue once that's complete.
