### ISSUE TITLE
Allow passing file-contents via Stdin

### ISSUE THREAD

**Issue by rvock** [brigade/scss-lint#465]
It would be nice, if the file contents could be passed via STDIN instead of a filename.

This would make it easier to use scss-lint in pre-commit hooks, which should work on the currently-staged file-contents and not the current-file in the filesystem.
You can get the currently staged file-contents via "git show :filename" but you would need to write it to a tempfile to check it with scss-lint.

**Comment by sds** [comment]
Hey @rvock, 

If I understand your request correctly, this would necessarily require that you could only lint one file at a time via STDIN unless you came up with some format to separate each file, which would be slow. This format would necessarily be arbitrary (unless there is a standard somewhere, though a quick search [doesn't reveal anything obvious to me](http://stackoverflow.com/questions/12594364/can-i-output-multiple-files-to-stdout-and-process-them-individually)). In general, I think it's probably easier for you to work with temporary files, as that way you can lint multiple files at a time.

I would encourage you to check out the [Overcommit](https://github.com/brigade/overcommit) project, which already has support for `scss-lint`, rather than write your own hooks.
