### ISSUE TITLE
is url("path") a quoted string?   

### ISSUE THREAD

**Issue by bassjobsen** [brigade/scss-lint#487]
`url("path")` gives `StringQuotes: Prefer single quoted strings` cause Sass does not have a url() function `url("path")` is an unquoted string (or valid CSS value) which contains quotes.

Although in the first place using double, single or even non quotes does not matter here: http://stackoverflow.com/questions/2168855/is-quoting-the-value-of-url-really-necessary

**Comment by sds** [comment]
I'm not sure I understand your question, @bassjobsen, but I'll try to answer.

Yes, the "path" inside `url("path")` is a quoted string. It has quotes around it, so it is treated by the Sass parser as a string.

If you do not want to require quotes around URLs, you can disable the [`UrlQuotes`](https://github.com/brigade/scss-lint/tree/master/lib/scss_lint/linter#urlquotes) linter using:

```yaml
linters:
  UrlQuotes:
    enabled: false
```

**Comment by bassjobsen** [comment]
Thanks for your quick answer.
What i tried to say. I think the complete `url("path")` is the string for the parser and `"path"` is only a part of this string. `url()` differs from `rgba()` cause Sass got its own `rgba()` function.

**Comment by sds** [comment]
I'm not sure where you are getting the impression that `url("path")` is the complete string for the parser. In this case, the Sass parser treats the URL as a [`Sass::Script::Tree::Funcall`](http://sass-lang.com/documentation/Sass/Script/Funcall.html), and the string inside as a `Sass::Script::Tree::Literal` (which wraps a `Sass::Script::Value::String`).

**Comment by bassjobsen** [comment]
From the same source you reference :) Sass::Script::Tree::Funcall:
>A function call either calls one of the functions in Functions, or if no function with the given name exists it returns a string representation of the function call.
As far as i understand url() is not one of the e functions in Functions, so a string representation of the function call will be returned.

**Comment by sds** [comment]
I'm still not clear on what exactly you are asking, @bassjobsen. Sorry if I'm missing something terribly obvious.

To me, the question you asked was: "does the Sass parser treat `url("path")` as a string?". The answer to this question is **no**. It is represented in the parse tree as a `Sass::Script::Tree::Funcall`. This is then rendered in the compiled CSS as a string, but that last step is obvious and not terribly interesting.

`url(path)` is treated differently, and will actually be treated as a raw [URL type as defined in the CSS spec](http://dev.w3.org/csswg/css-values/#url-value), in which case it is represented in the parse tree as a string (`Sass::Script::Tree::Literal wrapping a `Sass::Script::Tree::String`). `scss-lint`encourages you to use quotes in the URL so that the Sass parser represents the URL as a `Sass::Script::Tree::Funcall` instead of a single string, and you avoid some special escape character behavior of the raw URL literal referenced above. It also tends to syntax highlight better in some editors.

If your question revolves around whether `url` is a special built-in that gets evaluated like a Sass builtin function like `rgba`, then the answer is **no**, it is rendered as a regular string.
