### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by lencioni** [brigade/scss-lint#513]
I think it would be really great if SCSS-Lint had a better identity and I think that a good logo would go a long way. I figured I'd open this issue to collect ideas. I have some friends who have had reasonable luck using 99designs so something like that might be a reasonable option, but I think it would be best if it came from the community.

@ericam @hcatlin @malrase @jina you are active in the Sass community and either are or know good designers. Want to pitch in? ;) I'm thinking something pink would probably be the way to go, but after that I'm out of ideas.

**Comment by kaelig** [comment]
:+1:

**Comment by sds** [comment]
Quickly throwing something together from the [Sass brand page](http://sass-lang.com/styleguide/brand):

![screen shot 2016-02-20 at 6 21 17 pm](https://cloud.githubusercontent.com/assets/677877/13200492/9beb7462-d800-11e5-9e5e-18744ade0b4e.png)

I'm no designer, but if we're gunning for a 1.0 release as discussed in #725 then we should probably have _something_ as a logo. Would love other suggestions.

**Comment by lencioni** [comment]
I think this is a pretty good start! Here's my feedback:

- I think the icon should be on the left
- The text seems unbalanced with the icon. I think maybe either the icon is too small in comparison and/or the text is too bold. Maybe adjust the proportions a little?
- While I like the intention, I'm not 100% on the red dotted underline. It is pretty subtle, the color doesn't feel right, and it makes me feel like something is wrong. [JSCS](http://jscs.info/) uses a similar thing, but I think more effectively. I think we should just remove it.

Here's something I hacked up real quick based off of your idea. Typeface is Avenir Next (Medium and Italic) with a -1% letter spacing for better kerning. I like the italics because I think it implies that this tool can help your team go faster. I shortened and rounded off the sprocket teeth (although I wasn't able to get it just right because I was only working off of your image here, so it is a bit lopsided).

![scss-lint-logo](https://cloud.githubusercontent.com/assets/195534/13203453/83b59068-d86d-11e5-9ee1-09f0dd267f15.png)

Then I got the idea to combine your dotted line and the cog and came up with this:

![scss-lint-logo-dashed](https://cloud.githubusercontent.com/assets/195534/13203558/20da517e-d870-11e5-8c23-a6981d4c6441.png)

Which I quite like, although we'll need to fix the dashed line so each segment is the same size.

If you like one of these, I can try to work up a vector version. Although I don't have a vector program so I'll need to figure that out first, lol. Or, if you happen to have Illustrator or something handy and want to run with this, that sounds good to me too.

Also, I think we really need to chat with the Sass folks and make sure that it is okay to use their seal in our logo before we go forward with this concept. Once we agree on a concept, I'd be happy to reach out to them.

**Comment by sds** [comment]
Nice! I find your last one very aesthetically pleasing. The dotted lines maintain the playfulness of the original logo, which I think people associate with the Sass brand (at least I do).

We're good to manipulate the logo. The [Sass brand guidelines](http://sass-lang.com/styleguide/brand) mention the work is licensed under [Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License](https://creativecommons.org/licenses/by-nc-sa/3.0/deed.en_US), which means we can modify as long as we mention we modified it and link back. Their only usage rule is to be respectful in its use (no sexist imagery), and I think we're good on that front.

**Comment by lencioni** [comment]
Great sleuthing on the license. I reached out to Hampton anyway just to make sure we are cool, but I think he is in Japan so it might take him a while to get back to me.

**Comment by hcatlin** [comment]
I like it! It's fine usage-wise. If you want design blessing, ask Jina Bolton!






On Sun, Feb 21, 2016 at 7:57 AM -0800, "Joe Lencioni" <notifications@github.com> wrote:












I think this is a pretty good start! Here's my feedback:


I think the icon should be on the left
The text seems unbalanced with the icon. I think maybe either the icon is too small in comparison and/or the text is too bold. Maybe adjust the proportions a little?
While I like the intention, I'm not 100% on the red dotted underline. It is pretty subtle, the color doesn't feel right, and it makes me feel like something is wrong. JSCS uses a similar thing, but I think more effectively. I think we should just remove it.




Here's something I hacked up real quick based off of your idea. Typeface is Avenir Next (Medium and Italic) with a -1% letter spacing for better kerning. I like the italics because I think it implies that this tool can help your team go faster. I shortened and rounded off the sprocket teeth (although I wasn't able to get it just right because I was only working off of your image here, so it is a bit lopsided).







Then I got the idea to combine your dotted line and the cog and came up with this:







Which I quite like, although we'll need to fix the dashed line so each segment is the same size.



If you like one of these, I can try to work up a vector version. Although I don't have a vector program so I'll need to figure that out first, lol. Or, if you happen to have Illustrator or something handy and want to run with this, that sounds good to me too.



Also, I think we really need to chat with the Sass folks and make sure that it is okay to use their seal in our logo before we go forward with this concept. Once we agree on a concept, I'd be happy to reach out to them.

**Comment by connorshea** [comment]
I like the dashed line, although I think maybe "sass" should use a bolder weight and/or a rounded font? I also kind of preferred the pink text, but I don't feel too strongly on that front.

**Comment by jina** [comment]
I like the last logo on this page (dashed line, black text).

If you want some design feedback:
The kerning looks like it could use some love, but otherwise I'm fine with the font and weight. May I suggest trying to swap the weight&styles so that "lint" is more emphasized than the "scss" part?

But otherwise this is your project. Do as you like! :)

**Comment by lencioni** [comment]
Thanks @jina! I didn't have a proper image editing program so I couldn't adjust kerning letter-by-letter, but I was planning on tweaking all of that when I do it in vectors.

**Comment by sds** [comment]
I've gone ahead and added the logo in question to the README. Even if it still needs work, it looks "good enough" to me and gives the project a more welcoming home page.

Thanks for your work on this!
