### ISSUE TITLE
Lint core

### ISSUE THREAD

**Issue by wincent** [brigade/scss-lint#537]
@sds, you have a handful of lint gems now, including this one. Did you ever consider extracting the common core functionality out into a separate gem for re-use by the others? I'm thinking things like the runner, option-handling, file-system exploration etc, leaving language specific bits in the downstream gems.

Haven't even read the code, but thinking in the abstract, the thought occurred to me.

**Comment by sds** [comment]
Hey @wincent,

Yes, I have given this some (significant) thought. `haml-lint` and `slim-lint` are my attempt at converging on a design that is generalizable enough to be used in some form of generic linting framework. If you look at their code you'll notice they are (almost) exactly the same&mdash;this is intentional as I try to wrap my head around how to think about extracting a reusable framework from them. Unfortunately it's slow going as they aren't the top of my priority list.

Are you looking to create a linter of your own?

**Comment by wincent** [comment]
> Are you looking to create a linter of your own?

Nah. eslint has all my bases covered right now. I was just driving by and the thought occurred to me.
