### ISSUE TITLE
Error: env: ruby_executable_hooks

### ISSUE THREAD

**Issue by josedrac** [brigade/scss-lint#572]
With the new version, when I save de scss file it's showed this error.
![captura de pantalla 2015-08-29 a la s 12 35 22](https://cloud.githubusercontent.com/assets/5088801/9561553/7d3f5ed8-4e4a-11e5-8ff8-bbeb3e8aeaee.png)

Error: env: ruby_executable_hooks: No such file or directory
Error: env: ruby_executable_hooks: No such file or directory
  at exit (/Users/josedrac/.atom/packages/linter-scss-lint/node_modules/atom-linter/lib/helpers.coffee:29:24)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

To help fix this issue, please include:
- The above stack trace
- SCSS-Lint version: 0.41.0
- Sass version: 3.4.18
- Ruby version: 2.1.0

**Comment by sds** [comment]
Hey @josedrac,

Are you sure all that has changed is your `scss-lint` version? That error message references `ruby_executable_hooks`, which is not a file in `scss-lint`. The `No such file or directory` looks a standard missing file Ruby error message, but there's nothing from this report that allows me to deduce what the problem is. 

Can you raise the issue with the upstream editor you are using and get them to provide the stack trace of the Ruby process itself? That would help determine if this is indeed an issue with `scss-lint` or something else.

**Comment by sds** [comment]
Closing due to a lack of response, as well as the fact that the information given seems to suggest the problem does not lie with `scss-lint`.
