### ISSUE TITLE
Allow passing file-contents via stdin

### ISSUE THREAD

**Issue by steelbrain** [brigade/scss-lint#578]
I know this question has been asked before (#465) but my use-case is different. I am from the AtomLinter team and we're using this project in our `linter-scss-lint` package. We support both lintOnFly (lint as you type) and lint on save. To support lintOnFly for that provider, we'll have to get the current editor text and save it in a temp file and give that temp file to scss-lint to lint and then return those results, which means thousands of temp file would be created every few hours (AtomLinter/linter-scss-lint#72).

All of those temp files can be avoided if `scss-lint` supports passing file contents as stdin, if you would do so, You won't be the only one doing it, currently `eslint`, `coffeelint`, `jshint` and a lot of other linters provide similar options. In case you want to search your rcfile there or something, You could also add a parameter to specify path for the stdin file.

**Comment by sds** [comment]
Hey @steelbrain, thanks for your work on integrating `scss-lint` with the Atom editor.

Passing files via STDIN introduces a couple of edge cases, which I'm skeptical saving even thousands of temporary files every few hours is worth addressing. (that's not a lot of writes in my mind)

For example, one important question is what file path is the file passed via STDIN treated as having? `scss-lint` uses the file path in order to apply the correct configuration based on your `.scss-lint.yml`. I could easily see confusion from users piping a particular file to `scss-lint` and being surprised that linters they've disabled for that file in their configuration start reporting warnings.

This is a problem in general when you lint against a file with a different path than the original file you're linting&mdash;you're bound to run into situations where configuration you expect to be applied doesn't apply because of differences in the path.

I'm open to suggestions, but I think the pragmatic answer here is to stick with linting the file directly.

**Comment by steelbrain** [comment]
@sds I had specified the scenario about the file paths, `jshint` has a `--filename` argument, You can write to stdin and specify the path of the file there. It'll resolve the configuration files and all from there on automatically. so Yes, if you use that file path, You can read the `.scss-lint.yml` file automatically so no more linter re-enabling when they are disabled from the configuration file.

**Comment by sds** [comment]
Ah, sorry, I missed your last sentence. That makes sense. Happy to accept a pull request!

**Comment by steelbrain** [comment]
@sds I would **love** to send a PR but I don't know enough ruby to do that :(

**Comment by SpainTrain** [comment]
I also work on the scss-lint plugin for atom and know ruby reasonably well.  Maybe I can take a crack at this :smile_cat:

**Comment by lunaryorn** [comment]
Just for the record, Flycheck (a linting extension for Emacs) would profit from this feature as well :relaxed:

**Comment by sds** [comment]
Implemented in 8ad337a1a9d38f890b56ac355e44aadd36b7aa80. Thanks for the feedback!

**Comment by lunaryorn** [comment]
@sds Thank you.  That is great news!  😍

Mind if I ask whether there is an ETA for a release that includes this change?

**Comment by SpainTrain** [comment]
:clap: @sds you are awesome!

**Comment by sds** [comment]
@lunaryorn [0.43.0](https://github.com/brigade/scss-lint/releases/tag/v0.43.0) has just been released, but I would probably give it some time to settle given the number of new features going out. There tend to be a lot of bug reports, especially with new features whose behavior isn't fully comprehended until they're out in the wild.

**Comment by lunaryorn** [comment]
@sds I hate waiting for the cool things 😊

How long do you think will it take for the dust to settle?  Should we wait until the first bug fix release of 0.43?  Or should we wait for the next minor release?

**Comment by sds** [comment]
@lunaryorn I anticipate we'll push out a bugfix release by the end of this week.
