### ISSUE TITLE
Custom configuration .scss-lint.yml should replace default.yml

### ISSUE THREAD

**Issue by webfeature** [brigade/scss-lint#593]
At the moment we are using an old version of scss-lint with a self-created configuration file (.scss-lint.yml). Sometimes new employee install a newer version of scss-lint. In this case the linter is throwing more errors, because the .scss-lint.yml doesn't replace the default.yml.

**Comment by sds** [comment]
Hey @webfeature,

As long as the `.scss-lint.yml` exists in the directory that you are running `scss-lint` from, `scss-lint` merges that configuration with the `default.yml` configuration by design. This is to encourage adoption of new features as they are released.

We'll be changing the default configuration to disable all linters by default in the 1.0.0 release (see #564).
