### ISSUE TITLE
scss-lint messages

### ISSUE THREAD

**Issue by nnorton** [brigade/scss-lint#604]
Will scss-lint will ever return anything other than a warning or an error message? Also, what is the exact character that scss-lint returns upon a successful lint?

**Comment by sds** [comment]
Hey @nnorton,

`scss-lint` will output a stack trace if it fails unexpectedly due to a bug, but in general the contract for the default output format is to output a single line for each warning/error encountered. If there are no lints found, the default is to output nothing.

If you are trying to integrate `scss-lint` into some kind of build process, the [documentation on exit status codes](https://github.com/brigade/scss-lint#exit-status-codes) will probably be useful.

**Comment by lencioni** [comment]
Also, if you happen to be setting up scss-lint with a git pre-commit hook, you might want to [check out overcommit](https://github.com/brigade/overcommit), our extendable Git hook manager. It has scss-lint built in along with a whole bunch of other things that you might find useful. Here's a list: https://github.com/brigade/overcommit#built-in-hooks

If you decide to not use overcommit, this is our scss-lint integration that you might find useful: https://github.com/brigade/overcommit/blob/master/lib/overcommit/hook/pre_commit/scss_lint.rb
