### ISSUE TITLE
Should `initial` really trigger VariableForProperty?

### ISSUE THREAD

**Issue by abea** [brigade/scss-lint#662]
I require variables for colors and font-size properties. I just set a color to `initial` and got a flag for VariableForProperty. `inherit` does not trigger this warning, so it seems odd that `initial` would. Is there a reason for this or should this be fixed?

**Comment by chris-dura** [comment]
MDN recommends in this particular case that you might want to use `inherit` instead of `initial` since `color` is an inherited property:
https://developer.mozilla.org/en-US/docs/Web/CSS/initial

That being said, your question is still valid. It seems reasonably similar to the logical exceptions that already exist for things like `transparent` or `currentColor`.

**Comment by abea** [comment]
Fair. It's possible that `inherit` might work in my use case. I'll submit a PR adding `initial` since it doesn't seem totally crazy.

**Comment by abea** [comment]
Submitted pull request: https://github.com/brigade/scss-lint/pull/665/files

**Comment by sds** [comment]
Fixed in #665. Thanks!
