### ISSUE TITLE
Output to xml command not working

### ISSUE THREAD

**Issue by s10wen** [brigade/scss-lint#720]
I've tried a few things, but can't seem to get this working.

I'd like to use `-c` and `-f` but can't seem to get the command right.

This works fine:
```
scss-lint -c /path-to-config/.scss-lint.yml /path-to-scss/**/*.scss > ~/path-to-save-output/scss-lint.json
```

But:
```
scss-lint -f xml -c /path-to-config/.scss-lint.yml /path-to-scss/**/*.scss > ~/path-to-save-output/scss-lint.xml
```

Gives:
```
Invalid output format specified: xml
Run `scss-lint --help` for usage documentation
```

And:
```
scss-lint --format=Files -c /path-to-config/.scss-lint.yml /path-to-scss/**/*.scss | xargs xml > ~/path-to-save-output/scss-lint.xml
```

Looks like it runs, but then gives:
```
xargs: xml: No such file or directory
```

**Comment by lencioni** [comment]
`-f xml` isn't working for you because scss-lint does not have an xml formatter. More info on the available formatters: https://github.com/brigade/scss-lint#formatters

`| xargs xml` looks like it isn't working because you don't have an xml executable in your path. I'm not really sure what such an executable would do with the scss-lint output, but that definitely won't work unless you find or write `xml` and add it to somewhere in your path.

**Comment by s10wen** [comment]
Ahhhh, I misread the docs sorry, I'll look into `checkstyle`. Thanks.
