### ISSUE TITLE
vim & config

### ISSUE THREAD

**Issue by joaomilho** [brigade/scss-lint#751]
I'm using this with vim, but apparently it doesn't allow configuration like this: https://github.com/scrooloose/syntastic/wiki/Configuration-Files

Is there anything I'm missing?

**Comment by sds** [comment]
SCSS-Lint loads the `.scss-lint.yml` file from the current working directory, so you shouldn't need to specify a configuration explicitly.

If the issue is that you are editing a file and your current working directory does not have the `.scss-lint.yml` file, #516 is tracking adding support for ascending parent directories until an `.scss-lint.yml` file is found.
