### ISSUE TITLE
If the excludes glob returns no file, the command ends up excluding the actual allFiles

### ISSUE THREAD

**Issue by ijpiantanida** [brigade/scss-lint#754]
When the excludes option is set, but the glob doesn't return any file, the command will end up being `-e {actual allFiles}`.

Before adding the flag, it should be checked whether the argument is going to be empty.

**Comment by sds** [comment]
Using globs with the `-e` flag isn't supported, simply because this is not how shell expansion works.

Typically, your shell (`bash`/`zsh`, etc.) will take glob patterns and expand them _before_ executing the command.

The result is that if you have a glob that matches nothing, you'll end up with an empty string being interpolated into the command.

`scss-lint -e no-matches/*.scss` => `scss-lint -e`

`scss-lint -e matches/*.scss` => `scss-lint -e matches/one.scss matches/two.scss`

Notice that in the second case, only the first file is excluded. The second file is then interpreted as the file that `scss-lint` should lint (so ironically the exclusion is useless in this case).

Thus you shouldn't use globs for the `--exclude` flag. Hope this explains why!

**Comment by ijpiantanida** [comment]
OMG, this was the wrong repo.
I was trying to open the issue on ahmednuaman/grunt-scss-lint. 
That's what happens when you have 100 tabs open! Sorry about that!!
