### ISSUE TITLE
Can't load custom linters

### ISSUE THREAD

**Issue by renancouto** [brigade/scss-lint#818]
Hey!

I'm trying to develop a custom linter and use as `plugin_gems` dependency, but I get this error when I run:

```bash
Unable to load linter plugin gem 'scss_lint_plugin_example'. Try running `gem install scss_lint_plugin_example`, or adding it to your Gemfile and running `bundle install`. See the `plugin_gems` section of your .scss-lint.yml file to add/remove gem plugins.
```

I created a [repo](https://github.com/renancouto/scss-lint-test) that uses the [default example](https://github.com/cih/scss_lint_plugin_example) to show the error reproduced. One other thing, if I try importing the directory instead of using the gem, it works properly.

**Comment by sds** [comment]
Hey @renancouto,

Have you actually installed the gem plugin with `gem build scss_lint_plugin_example.gemspec && gem install scss_lint_plugin_example-0.0.1.gem` (substituting the correct version) so that `require 'scss_lint_plugin_example'` works?

If you're actively developing the gem and using Bundler you can also run `bundle config local.scss_lint_plugin_example /path/to/local/git/repository` in the repository for which you're using SCSS-Lint + the plugin. See http://bundler.io/v1.12/man/bundle-config.1.html#LOCAL-GIT-REPOS for documentation.

**Comment by sds** [comment]
Hey @renancouto,

Have you actually installed the gem plugin with `gem build scss_lint_plugin_example.gemspec && gem install scss_lint_plugin_example-0.0.1.gem` (substituting the correct version) so that `require 'scss_lint_plugin_example'` works?

If you're actively developing the gem and using Bundler you can also run `bundle config local.scss_lint_plugin_example /path/to/local/git/repository` in the repository for which you're using SCSS-Lint + the plugin. See http://bundler.io/v1.12/man/bundle-config.1.html#LOCAL-GIT-REPOS for documentation.
