### ISSUE TITLE
Looks like Ruby Sass is going away in 1 year

### ISSUE THREAD

**Issue by lencioni** [brigade/scss-lint#867]
http://blog.sass-lang.com/posts/1022316-announcing-dart-sass

> Ruby Sass, on the other hand, will eventually go away unless a new maintainer appears. We don't want to make the transition sudden and risk fracturing the ecosystem: Chris and I are committed to maintaining it for one year, which includes keeping the language in sync with any new additions in Dart Sass. If anyone is interested in volunteering as a maintainer after that period, we'd be thrilled to mentor them and teach them the codebase over the coming year. But if no one steps up, Ruby Sass will be officially considered deprecated and unmaintained.

It seems like we will need to figure out the path forward for scss-lint. Here are a few options I can think of:

1. Rewrite this project in Dart or JavaScript, and keep depending on Sass directly.
1. Step up to maintain Ruby Sass in parallel with Dart Sass.
1. Write and maintain our own parser in Ruby.
1. Deprecate scss-lint in favor of [stylelint](http://stylelint.io/).

The last option seems the most appealing to me. I think that stylelint has probably done the hard work for us already (it can understand SCSS syntax), has some nice features (e.g. autofix via [stylefmt](https://github.com/morishitter/stylefmt)), and a lot of users. It might be best to join forces. Thoughts?

**Comment by DanPurdy** [comment]
Just to throw my 2 cents in here, If you decide to take the Javascript route you could always come over and contribute to [Sass-lint](https://github.com/sasstools/sass-lint). It has support for both Sass and scss format which stylelint currently doesn't have (outside of experimental) and while we've been ironing out issues with the AST we use we're certain that more contributors would only help improve that situation! 

We're already a pretty established alternative to your ruby implementation here and have certainly taken notice of many issues you've come up against and also followed certain rule implementations you had so as to not split the consensus between the two linters having personally been big scss-lint users in the past!

**Comment by sds** [comment]
Thanks for bringing this up, @lencioni.

I don't think there is any bandwidth to support the upstream Ruby Sass implementation or maintain our own parser, and a rewrite seems unnecessary given the other tools out there.

I've added a notice to the README which mentions stylelint and sass-lint, which both seem like excellent alternatives (though I personally have no experience with either).

We'll keep the project running as it's been running (that is, accepting pull requests from the community and answering simple support questions) but otherwise it seems like the time has come for the community to shift to something new. I've no doubt that Natalie and the rest of the core Sass team will do an excellent job with the new Dart implementation!

**Comment by lencioni** [comment]
We had a good run here. Thanks for all of your hard work on this project @sds (and other contributors)! I know that SCSS-Lint has saved me and the teams I've been on a lot of time and effort.

**Comment by tdooner** [comment]
👏 Well done, scss-lint team, especially @sds and @lencioni. This is a high quality piece of software that I am sad about its impending shutdown. You guys have rocked it this whole time. @sds especially, has put an incredible amount of time into this.
